#ifndef BASICINFONMAINTAIN_GLOBAL_H
#define BASICINFONMAINTAIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASICINFONMAINTAIN_LIBRARY)
#  define BASICINFONMAINTAIN_EXPORT Q_DECL_EXPORT
#else
#  define BASICINFONMAINTAIN_EXPORT Q_DECL_IMPORT
#endif

#endif // BASICINFONMAINTAIN_GLOBAL_H
